### ISSUE TITLE
Add ros_packages to ros_install role.

### ISSUE THREAD

**Issue by markpitchless** [shadow-robot/sr-build-tools#39]
Add a variable to install additional ROS packages along with the main ros install. e.g.

``` yaml
ros_release: 'hydro'
ros_packages:
  - 'shadow-robot-ethercat'
  - 'shadow-robot'
```

Would install `ros-hydro-shadow-robot` and `ros-hydro-shadow-robot-ethercat` along with the main ros packages.

Will be in `ansible/roles/ros_install/tasks/main.yml`
